//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsWorkers
    {
        public int GroupsWorkersID { get; set; }
        public int GroupID { get; set; }
        public int WorkerID { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
