//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutors
    {
        public int TutorID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> OrgainsationID { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Organisations Organisations { get; set; }
    }
}
